name: Unit Tests

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  Unit-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path './tests' -OutputFormat NUnitXml -OutputFile './TestResults/results.xml'
        continue-on-error: true
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./TestResults/results.xml
          
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pester Tests
          path: ./TestResults/results.xml
          reporter: dotnet-nunit
    
